// import React from 'react'
// import './Home.css'
// import chat1 from './../../../../assets/chat1.png'
// import chat2 from './../../../../assets/chat2.png'


// function HomeCard() {
//     return (
             
//         <div className='main'>
//             <div className='left'>
//                 <img src={chat1} alt="avatar" />
//             </div>
//             <div className='middle'>
//                 <h1> 👋 Hello There </h1>
//                 <h3> What do you know about Mearnstack?</h3>
               
//             </div>
//             <div className='right'>
//                 <img src={chat2} alt="avatar" />

//             </div>
//         </div>
//     )
// }

// export default HomeCard
